# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'bookingwebapp:$(build.buildId)'

steps:
- script: npm install
  displayName: 'Node Install'
- script: npm run build
  displayName: 'Node Build Project'
- script: docker build -f Dockerfile -t $(dockerId).docker.io/$(dockerId)/$(imageName) .
  displayName: 'Docker Image Build'
- script: docker login -u $(dockerId) -p $(pswd) $(dockerId).docker.io
  displayName: 'ACR Login'
- script: docker push $(dockerId).docker.io/$(dockerId)/$(imageName)
  displayName: 'ACR Image Push'